[theme]
base="light"
primaryColor="#ff8000"              # JET Orange - From JET color palette
backgroundColor="#efedea"           # Mozzarella - From JET color palette
secondaryBackgroundColor="#C1DADE"  # Cupcake - From JET color palette
textColor="#242E30"                 # Charcoal - From JET color palette
font="sans serif"
